name: Integration Tests

on:
  pull_request:
  push:
    branches: [main]


jobs:
  build_and_test:
    name: Build and test the connector
    runs-on: ubuntu-latest
    steps:
      - name: build the connector
        run: |
          pwd
          ls
          make build_connector