name: Integration Tests

on:
  pull_request:
  push:
    branches: [main]


jobs:
  build_and_test:
    name: Build and test the connector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: whatever
        run: |
          echo "***** cmakelists hash = " ${{ hashFiles('./CMakeLists.txt')
      - uses: actions/cache@v3
        id: cache-deps
        with:
          key: fivetran-deps-${{ hashFiles('./CMakeLists.txt') }}
          path: ./install

      - name: build the dependencies
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        run: |
          make build_dependencies

      - name: build the connector
        run: |
          make build_connector

      - name: run tests
        env:
          motherduck_token: ${{ secrets.CI_TESTING_TOKEN }}
        run: |
          ./build/Release/integration_tests